---
sidebar: sidebar 
permalink: create-knowledgebase.html 
keywords: ai, chatbot, creating, knowledge base 
summary: 在您部署 AI 基礎架構、並從適用於 ONTAP 資料存放區的 FSX 中找出要整合到知識庫的資料來源之後、您就可以使用 Workload Factory 來建置知識庫。在本步驟中、您也將定義 AI 特性、並建立對話前人。 
---
= 建立知識庫
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在您部署 AI 基礎架構、並從適用於 ONTAP 資料存放區的 FSX 中找出要整合到知識庫的資料來源之後、您就可以使用 Workload Factory 來建置知識庫。在本步驟中、您也將定義 AI 特性、並建立對話前人。

您可以使用知識庫、而無需整合組織的資料來源。在這種情況下、與知識庫整合的應用程式只會提供來自網際網路上公開資訊的結果。這稱為 _public 模式 _ 整合。

在大多數情況下、您會想要將組織的資料來源整合到知識庫中。這稱為 _ 企業模式 _ 整合、因為它能提供企業的知識。



== 建立及設定知識庫

知識庫定義了您想要用來建立知識庫的特性、例如基礎 AI 模型和內嵌格式。

.步驟
. 登入 Workload Factory 。
. 在 AI 工作負載方塊中、選取 * 建立 Chatbot* 。
. 從「知識庫」標籤中、選取 * 新增知識庫 * 。
. 在「定義知識庫」頁面中、設定知識庫設定：
+
.. * 名稱 * ：輸入您要用於知識庫的名稱。
.. * 說明 * ：輸入知識庫的詳細說明。
.. * 內嵌模型 * ：內嵌模型定義如何將資料轉換成知識庫的向量內嵌。Workload Factory 支援下列機型：
+
*** Titan 嵌入式 G1 - 文字
*** Titan 內嵌文字 v2
*** Titan Multic形式 嵌入式 G1
+
請注意、您必須已啟用 Amazon bedrock 的內嵌模型。

+
https://aws.amazon.com/bedrock/titan/["深入瞭解 Amazon Titan"^]



.. * 聊天模式 * ：選擇與 Amazon bedrock 整合的 Claude 聊天模式。請注意、您必須已啟用 Amazon Bedrock 的聊天模式。
+
深入瞭解可選擇的機型、協助您選擇： https://aws.amazon.com/bedrock/claude/["Anthropic 在 Amazon bedrock 的 Claude"^]

.. * 對話開場白 * ：選擇是否要提供最多四個對話啟動器提示、讓與使用此知識庫的聊天機器人程式互動的使用者看到。建議您啟用此設定。
+
如果您確實啟動對話啟動器、預設會選取「自動模式」。只有在您將資料來源新增至知識庫之後、才能啟用「手動模式」。link:manage-knowledgebase.html["瞭解如何修改知識庫設定"]。



. 選取 * 建立知識庫 * 、將知識庫新增至 GenAI 。
. 在精靈的下一頁中、您可以選擇將資料來源新增至新知識庫、或是在此結束程序而不新增資料來源。建議您選擇 * 新增資料來源 * 、然後立即新增一或多個資料來源。




== 將資料來源新增至知識庫

您可以新增一或多個資料來源、以便將組織的資料填入知識庫。

.關於這項工作
支援的資料來源數量上限為 10 個。

.步驟
. 選取 * 新增資料來源 * 後、將會顯示 * 選取檔案系統 * 頁面。
. * 選取檔案系統 * ：選取資料來源檔案所在的 ONTAP 檔案系統的 FSX ，然後選取 * 下一步 * 。
. * 選取磁碟區 * ：選取資料來源檔案所在的磁碟區、然後選取 * 下一步 * 。
+
選取使用 SMB 傳輸協定儲存的檔案時、您需要輸入 Active Directory 資訊、其中包括網域、 IP 位址、使用者名稱和密碼。

. * 選取資料來源 * ：根據您儲存檔案的位置選取資料來源位置。這可以是整個磁碟區、或只是磁碟區中的特定資料夾或子資料夾、然後選取 * 下一步 * 。
. * 定義 AI 參數 * ：在 * 區塊定義 * 區段中、定義在查詢 Amazon 基礎所屬的知識庫時、 Amazon 基礎服務如何將資料來源內容分割成區塊。此時、您只能選擇句子。
. 在 * 權限感知 * 區段中、只有當您選取的資料來源位於使用 SMB 通訊協定的磁碟區上時、才能使用、您可以啟用或停用選取：
+
** * 已啟用 * ：存取此知識庫的聊天機器人程式使用者只能從其存取的資料來源取得查詢回應。
** * 停用 * ：聊天機器人程式的使用者將會使用所有整合式資料來源的內容接收回應。


. 選取 * 新增 * 將此資料來源新增至您的知識庫。


.結果
資料來源開始內嵌到您的知識庫中。資料來源完全內嵌時、狀態會從「內嵌」變更為「內嵌」。

將單一資料來源新增至知識庫之後、您可以在 Chatbot 模擬器視窗中進行本機測試、並在將聊天機器人提供給使用者之前進行任何必要的變更。您也可以依照相同步驟、將其他資料來源新增至知識庫。
